// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nacos_grpc_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Nacos.Grpc.GrpcService {
  public static partial class NacosTransport
  {
    static readonly string __ServiceName = "NacosTransport";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Nacos.Grpc.GrpcService.Payload> __Marshaller_Payload = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nacos.Grpc.GrpcService.Payload.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Nacos.Grpc.GrpcService.Payload, global::Nacos.Grpc.GrpcService.Payload> __Method_RequestStream = new grpc::Method<global::Nacos.Grpc.GrpcService.Payload, global::Nacos.Grpc.GrpcService.Payload>(
        grpc::MethodType.ServerStreaming,
        "RequestStream",
        "requestStream",
        __Marshaller_Payload,
        __Marshaller_Payload);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Nacos.Grpc.GrpcService.Payload, global::Nacos.Grpc.GrpcService.Payload> __Method_Request = new grpc::Method<global::Nacos.Grpc.GrpcService.Payload, global::Nacos.Grpc.GrpcService.Payload>(
        grpc::MethodType.Unary,
        "Request",
        "request",
        __Marshaller_Payload,
        __Marshaller_Payload);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Nacos.Grpc.GrpcService.Payload, global::Nacos.Grpc.GrpcService.Payload> __Method_BiStreamRequest = new grpc::Method<global::Nacos.Grpc.GrpcService.Payload, global::Nacos.Grpc.GrpcService.Payload>(
        grpc::MethodType.DuplexStreaming,
        "BiRequestStream",
        "requestBiStream",
        __Marshaller_Payload,
        __Marshaller_Payload);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Nacos.Grpc.GrpcService.NacosGrpcServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for NacosTransport</summary>
    public partial class NacosTransportClient : grpc::ClientBase<NacosTransportClient>
    {
      /// <summary>Creates a new client for NacosTransport</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public NacosTransportClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NacosTransport that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public NacosTransportClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected NacosTransportClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected NacosTransportClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///请求Stream返回
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Nacos.Grpc.GrpcService.Payload> RequestStream(global::Nacos.Grpc.GrpcService.Payload request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RequestStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///请求Stream返回
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Nacos.Grpc.GrpcService.Payload> RequestStream(global::Nacos.Grpc.GrpcService.Payload request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_RequestStream, null, options, request);
      }
      /// <summary>
      ///请求
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Nacos.Grpc.GrpcService.Payload Request(global::Nacos.Grpc.GrpcService.Payload request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Request(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///请求
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Nacos.Grpc.GrpcService.Payload Request(global::Nacos.Grpc.GrpcService.Payload request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Request, null, options, request);
      }
      /// <summary>
      ///请求
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Nacos.Grpc.GrpcService.Payload> RequestAsync(global::Nacos.Grpc.GrpcService.Payload request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RequestAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///请求
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Nacos.Grpc.GrpcService.Payload> RequestAsync(global::Nacos.Grpc.GrpcService.Payload request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Request, null, options, request);
      }
      /// <summary>
      ///双向流请求
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Nacos.Grpc.GrpcService.Payload, global::Nacos.Grpc.GrpcService.Payload> BiStreamRequest(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BiStreamRequest(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///双向流请求
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Nacos.Grpc.GrpcService.Payload, global::Nacos.Grpc.GrpcService.Payload> BiStreamRequest(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_BiStreamRequest, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override NacosTransportClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NacosTransportClient(configuration);
      }
    }

  }
}
#endregion
